server:
  shutdown: graceful
spring:
  main:
    banner-mode: "off"
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: my-exercise
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
